config/routes.rb
SmwSmw::Application.routes.draw do

  root :to => 'home#index'

  match 'home/:id' => 'home#admin'

  match 'admin_edit_listing/:id' => 'listings#admin_edit'

  match 'listings_admin/:id' => 'listings#admin'

  match 'login' => 'user_sessions#new', :as => :login

  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'searchautos' => 'autolistings#searchautos', :as => :searchautos
  match 'searchmotos' => 'motolistings#searchmotos', :as => :searchmotos
  match 'searchmarine' => 'marinelistings#searchmarine', :as => :searchmarine
  match 'searchpower' => 'powerlistings#searchpower', :as => :searchpower

  match 'about' => 'home#about', :as => :about

  match 'contact' => 'home#contact', :as => :contact

  match 'faq' => 'home#faq', :as => :faq

  match 'whatiwant' => 'whatiwant#whatiwant', :as => :whatiwant

  match 'basicsearch' => 'listings#basicsearch', :as => :basicsearch

  match 'newmain' => 'listings#newmain', :as => :newmain

  match 'newmain' => 'listings#newmain', :as => :newmain

  match 'photos/:id' => 'photos#showlarge', :as => :largephoto

  match 'medphoto/:id' => 'photos#showmedium', :as => :medphoto

  match 'smallphoto/:id' => 'photos#showsmall', :as => :smallphoto

  match 'inbox' => 'messages#inbox', :as => :inbox

  match 'sent' => 'messages#sent', :as => :sent

  resources :messages do
    member do
      delete 'deletesent'
      get 'reply'
    end
  end

  match 'privacypolicy' => 'home#privacypolicy', :as => :privacypolicy

  match 'visitoragreement' => 'home#visitoragreement', :as => :visitoragreement

   resources :wishlists
   resources :favorites
   resources :messages
   resources :users, :has_many=>:listings

   resources :listings do
    resources :photos
   end

   resources :user_sessions

   resources :users, :shallow => true do
    resources :listings, :name_prefix => nil do
      resources :photos
    end
    resources :wishlists
    resources :favorites
  end

   resources :password_resets
   resources :autocategories
   resources :automodels
   resources :marinecategories
   resources :marinemakes
   resources :motocategories
   resources :motomakes
   resources :powercategories
   resources :powermakes
   resources :autolistings
   resources :motolistings
   resources :marinelistings
   resources :powerlistings

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :listing
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # GET /favorites
  # GET /favorites.xml
  def index
  	@user = current_user
  	if @user
	    @favorites = @user.favorites.find(:all, :include => {:listing => :photos})
	  end
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @favorites }
    end
  end

  # GET /favorites/1
  # GET /favorites/1.xml
#  def show
#    @favorite = Favorite.find(params[:id])
#
#    respond_to do |format|
#      format.html # show.html.erb
#      format.xml  { render :xml => @favorite }
#    end
#  end

  # GET /favorites/new
  # GET /favorites/new.xml
  def new
    @favorite = Favorite.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @favorite }
    end
  end

  # POST /favorites
  # POST /favorites.xml
  def create
    @favorite = Favorite.new(params[:favorite])

    respond_to do |format|
      if @favorite.save
        flash[:notice] = 'Favorite was successfully created.'
        format.html { redirect_to :back }
        format.xml  { render :xml => @favorite, :status => :created, :location => @favorite }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @favorite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.xml
  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy

    respond_to do |format|
    	flash[:notice] = 'Favorite was successfully removed.'
      format.html { redirect_to(favorites_path) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/edit.html.erb
<h1>Editing favorite</h1>

<% form_for(@favorite) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </p>
  <p>
    <%= f.label :listing %><br />
    <%= f.text_field :listing %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div>
<% end %>
<% if @user %>
	<table width="100%" border="1" cellpadding="0" cellspacing="0" bordercolor="#823416" class="searchResultsTable">
		<h3>My Favorites</h3>
		<tr>
			<th height="25" align="left"></th>
			<th height="25" align="left">Year</th>
			<th height="25" align="left">Make</th>
			<th height="25" align="left">Model</th>
			<th height="25" align="left">Trans</th>
			<th height="25" align="left">Mileage</th>
			<th height="25" align="left">Price</th>
			<th height="25" align="left"></th>
		</tr>
		<br/>

		<% @favorites.each do |favorite| %>
		<tr>
			<td align="center">
				<% favorite.listing.photos.all(:limit => 1).each do |photo| %>
					<%= link_to image_tag(smallphoto_url(photo, :jpg), :alt => photo.name, :border => 0), listing_path(favorite.listing) %><br/>
				<% end %>
				<%=h favorite.listing.photos.all.count %>
				<% if favorite.listing.photos.all.count == 1 %>
					&nbsp;Photo<br/>
				<% elsif favorite.listing.photos.all.count == 0 %>
					&nbsp;Photos<br/>
				<% else %>
					&nbsp;Photos<br/>
					<%= link_to image_tag("more_photos.png", :alt => "more photos", :size => "74x10", :border => "0"), favorite %>
					</a>
				<% end %>
			</td>
			<td align="center" valign="middle">
				<%=h favorite.listing.year %>
			</td>
			<td align="center" valign="middle">
				<%=h favorite.listing.make %>
			</td>
			<td align="center" valign="middle">
				<%=h favorite.listing.model %>
			</td>
			<td align="center" valign="middle">
				<%=h favorite.listing.transmission %>
			</td>
			<td align="center" valign="middle">
				<%=h favorite.listing.mileage %>
			</td>
			<td align="center" valign="middle">
				<%=h favorite.listing.price %>
			</td>
			<td align="center" valign="middle">
				<%=h favorite.listing.owner.username %>
			</td>
			<td>
				<%= link_to "Remove", favorite, :confirm => 'Are you sure?', :method => :delete %>
		</tr>
		
		<% end %>
		
	</table>
	
	<p>&nbsp;</p>

	<div align="center">
		<a href="http://www.camaroforumz.com" target="_blank">
			<img src="../images/Ads/Camaro-forumAd.jpg" width="382" height="60" alt="camaroforumz.com" border="0" />
		</a>
		<a href="http://www.dpbolvw.net/click-3732474-10518038" target="_blank">
<img src="http://www.awltovhc.com/image-3732474-10518038" width="468" height="60" alt="$100 Mail-in Rebate on Mickey Thompson Tires & Whe" border="0"/></a>
	</div>

	<br />
	
<% else %>

	<table width="883" border="0" cellpadding="10" cellspacing="0">
		<tr>
			<td align="center" valign="top">
				<p><%= link_to "Register", new_user_path %> or <%= link_to "Log in", login_url %> to set up your "Favorites" list - this will help you track the vehicles you like.<br/>
				</p>
			</td>
		</tr>
		<tr align="center">
			<td>
<!--				<a href="http://www.camaroforumz.com" target="_blank">
					<img src="../images/Ads/Camaro-forumAd.jpg" width="382" height="60" alt="camaroforumz.com" border="0" />
				</a>
-->
				<a href="javascript:gotoshow()">
					<img src="../images/banners/MoparNation.jpg" name="slide" border=0 style="filter:blendTrans(duration=3)" width=382 height=60>
				</a>
				<a href="http://www.dpbolvw.net/click-3732474-10518038" target="_blank">
<img src="http://www.awltovhc.com/image-3732474-10518038" width="468" height="60" alt="$100 Mail-in Rebate on Mickey Thompson Tires & Whe" border="0"/></a>
			</td>
		</tr>
	</table>
	
<% end %>

app/views/favorites/new.html.erb
<h1>New favorite</h1>

<% form_for(@favorite) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </p>
  <p>
    <%= f.label :listing %><br />
    <%= f.text_field :listing %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', favorites_path %>