config/routes.rb
SmwSmw::Application.routes.draw do

  root :to => 'home#index'

  match 'home/:id' => 'home#admin'

  match 'admin_edit_listing/:id' => 'listings#admin_edit'

  match 'listings_admin/:id' => 'listings#admin'

  match 'login' => 'user_sessions#new', :as => :login

  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'searchautos' => 'autolistings#searchautos', :as => :searchautos
  match 'searchmotos' => 'motolistings#searchmotos', :as => :searchmotos
  match 'searchmarine' => 'marinelistings#searchmarine', :as => :searchmarine
  match 'searchpower' => 'powerlistings#searchpower', :as => :searchpower

  match 'about' => 'home#about', :as => :about

  match 'contact' => 'home#contact', :as => :contact

  match 'faq' => 'home#faq', :as => :faq

  match 'whatiwant' => 'whatiwant#whatiwant', :as => :whatiwant

  match 'basicsearch' => 'listings#basicsearch', :as => :basicsearch

  match 'newmain' => 'listings#newmain', :as => :newmain

  match 'newmain' => 'listings#newmain', :as => :newmain

  match 'photos/:id' => 'photos#showlarge', :as => :largephoto

  match 'medphoto/:id' => 'photos#showmedium', :as => :medphoto

  match 'smallphoto/:id' => 'photos#showsmall', :as => :smallphoto

  match 'inbox' => 'messages#inbox', :as => :inbox

  match 'sent' => 'messages#sent', :as => :sent

  resources :messages do
    member do
      delete 'deletesent'
      get 'reply'
    end
  end

  match 'privacypolicy' => 'home#privacypolicy', :as => :privacypolicy

  match 'visitoragreement' => 'home#visitoragreement', :as => :visitoragreement

   resources :wishlists
   resources :favorites
   resources :messages
   resources :users, :has_many=>:listings

   resources :listings do
    resources :photos
   end

   resources :user_sessions

   resources :users, :shallow => true do
    resources :listings, :name_prefix => nil do
      resources :photos
    end
    resources :wishlists
    resources :favorites
  end

   resources :password_resets
   resources :autocategories
   resources :automodels
   resources :marinecategories
   resources :marinemakes
   resources :motocategories
   resources :motomakes
   resources :powercategories
   resources :powermakes
   resources :autolistings
   resources :motolistings
   resources :marinelistings
   resources :powerlistings

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :email, :firstname, :lastname, :phone, :address, :address2, :city, :state, :zip, :username, :password,
                  :password_confirmation, :referred_by

	validates :firstname, :lastname, :phone, :address, :city, :state, :zip, :referred_by, :presence => true
	validates :zip, :length => { :in => 5..6 }

#can't make zip all numeric any more since Canadian Postal Codes are alphanumeric
	#validates_numericality_of :zip, :only_integer => true
	
	has_many :listings, :dependent => :destroy
	has_many :messages
	has_many :sent_messages, :class_name => "Message", :foreign_key => "sender_id", :conditions => ['sender_deleted_at IS NULL'], :order => "created_at DESC"
	has_many :received_messages, :class_name => "Message", :foreign_key => "recipient_id", :conditions => ['recipient_deleted_at IS NULL'], :order => "created_at DESC"
	has_many :unread_messages, :class_name => "Message", :foreign_key => "recipient_id", :conditions => ['read_at IS NULL AND recipient_deleted_at IS NULL'], :order => "created_at DESC"
	has_many :wishlists
	has_many :favorites
	#has_many :favorite_listings, :through => :favorites, :source => :listing
	acts_as_authentic
	
def deliver_password_reset_instructions!
	reset_perishable_token!
	Automailer.deliver_password_reset_instructions(self)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = current_user
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])
    @user.city = params[:user][:city].titleize

    respond_to do |format|
      if @user.save
        flash[:notice] = 'Registration successful.'
        format.html { redirect_to newmain_path }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = current_user

    respond_to do |format|
      if @user.update_attributes(params[:user])
        flash[:notice] = 'Profile successfully updated.'
        format.html { redirect_to root_url }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<table width="100%" border="0" cellpadding="20" cellspacing="0">
	<tr>
		<td align="left" valign="top">
			<h3>Edit User Profile<br /></h3>
			
			<% form_for(@user) do |f| %>
				<table width="830" border="0" cellspacing="1" cellpadding="1">
					<tr>
						<%= f.error_messages %>

						<td width="16%" height="20" class="formText">
							<%= f.label :email %>
						</td>
            <td>
            	<%= f.text_field :email %>
            </td>
            <td width="25%" rowspan="14" align="center" valign="top">
            	<%= image_tag "formPics1.png", :alt => "Register To Swap Your Whip!", :size => "151x250" %>
            </td>
          </tr>
          <tr>
						<td width="16%" height="20" class="formText">
							<%= f.label :first_name %>
						</td>
						<td>
							<%= f.text_field :firstname %>
						</td>
					</tr>
					<tr>
						<td width="16%" height="20" class="formText">
							<%= f.label :last_name %>
						</td>
						<td>
							<%= f.text_field :lastname %>
						</td>
					</tr>
					<tr>
						<td width="16%" height="20" class="formText">
							<%= f.label :phone %>
						</td>
						<td>
							<%= f.text_field :phone %>
						</td>
					</tr>
					<tr>
						<td width="16%" height="20" class="formText">
							<%= f.label :address %>
						</td>
						<td>
							<%= f.text_field :address %>
						</td>
					</tr>
					<tr>
						<td width="16%" height="20" class="formText">
							<%= f.label :address2 %>
						</td>
						<td>
							<%= f.text_field :address2 %>
						</td>
					</tr>
					<tr>
						<td width="16%" height="20" class="formText">
							<%= f.label :city %>
						</td>
						<td>
							<%= f.text_field :city %>
						</td>
					</tr>
					<tr>
						<td width="16%" height="20" class="formText">
							<%= f.label "State/Province" %>
						</td>
						<td>
							<%= f.select(:state, ['AK','AL','Alberta','AR','AZ','British Columbia','CA','CO','CT','DE','FL','GA','HI','IA','ID','IL','IN','KS','KY','LA','MA','Manitoba','MD','ME','MI','MN','MO','MS','MT','NC','ND','NE','New Brunswick','Newfoundland and Labrador','NH','NJ','NM','Nova Scotia','NV','NY','OH','OK','Ontario','OR','PA','Prince Edward Island','Quebec','RI','Saskatchewan','SC','SD','TN','TX','UT','VA','VT','WA','WI','WV','WY'], {:prompt => "-Select State/Province"}) %>
						</td>
					</tr>
					<tr>
						<td width="16%" height="20" class="formText">
							<%= f.label "Zip/Postal Code" %>
						</td>
						<td>
							<%= f.text_field :zip %>
						</td>
					</tr>
					<tr>
						<td width="16%" height="20" class="formText">
							<%= f.label :username %>
						</td>
						<td>
							<%= f.text_field :username %>
						</td>
					</tr>
					<tr>
						<td width="16%" height="20" class="formText">
							<%= f.label :password %>
						</td>
						<td>
							<%= f.password_field :password %>
						</td>
					</tr>
					<tr>
						<td width="16%" height="20" class="formText">
							<%= f.label :password_confirmation %>
						</td>
						<td>
							<%= f.password_field :password_confirmation %>
						</td>
					</tr>
					<tr>
						<td colspan="2">&nbsp;</td>
					</tr>
					<tr>
						<td>
							<%= image_submit_tag("update_button.jpg", :alt => "Update", :size => "79x28", :border => 0) %>
						</td>
						<td>&nbsp;</td>
          </tr>
          <tr>
            <td colspan="2">&nbsp;</td>
            <td align="center" valign="top">&nbsp;</td>
          </tr>
          <tr>
            <td colspan="3" class="infoText">
            	<%= link_to 'Create Listing', new_user_listing_path(@user) %>
            </td>
          </tr>
				</table>

			<% end %>

		</td>
	</tr>
</table>

app/views/users/indexDONOTUSE.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Password</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%=h user.username %></td>
    <td><%=h user.email %></td>
    <td><%=h user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New user', new_user_path %>

app/views/users/showDONOTUSE.html.erb
<p>
  <b>Username:</b>
  <%=h @user.username %>
</p>

<p>
  <b>Email:</b>
  <%=h @user.email %>
</p>

<p>
  <b>Password:</b>
  <%=h @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>