config/routes.rb
SmwSmw::Application.routes.draw do

  root :to => 'home#index'

  match 'home/:id' => 'home#admin'

  match 'admin_edit_listing/:id' => 'listings#admin_edit'

  match 'listings_admin/:id' => 'listings#admin'

  match 'login' => 'user_sessions#new', :as => :login

  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'searchautos' => 'autolistings#searchautos', :as => :searchautos
  match 'searchmotos' => 'motolistings#searchmotos', :as => :searchmotos
  match 'searchmarine' => 'marinelistings#searchmarine', :as => :searchmarine
  match 'searchpower' => 'powerlistings#searchpower', :as => :searchpower

  match 'about' => 'home#about', :as => :about

  match 'contact' => 'home#contact', :as => :contact

  match 'faq' => 'home#faq', :as => :faq

  match 'whatiwant' => 'whatiwant#whatiwant', :as => :whatiwant

  match 'basicsearch' => 'listings#basicsearch', :as => :basicsearch

  match 'newmain' => 'listings#newmain', :as => :newmain

  match 'newmain' => 'listings#newmain', :as => :newmain

  match 'photos/:id' => 'photos#showlarge', :as => :largephoto

  match 'medphoto/:id' => 'photos#showmedium', :as => :medphoto

  match 'smallphoto/:id' => 'photos#showsmall', :as => :smallphoto

  match 'inbox' => 'messages#inbox', :as => :inbox

  match 'sent' => 'messages#sent', :as => :sent

  resources :messages do
    member do
      delete 'deletesent'
      get 'reply'
    end
  end

  match 'privacypolicy' => 'home#privacypolicy', :as => :privacypolicy

  match 'visitoragreement' => 'home#visitoragreement', :as => :visitoragreement

   resources :wishlists
   resources :favorites
   resources :messages
   resources :users, :has_many=>:listings

   resources :listings do
    resources :photos
   end

   resources :user_sessions

   resources :users, :shallow => true do
    resources :listings, :name_prefix => nil do
      resources :photos
    end
    resources :wishlists
    resources :favorites
  end

   resources :password_resets
   resources :autocategories
   resources :automodels
   resources :marinecategories
   resources :marinemakes
   resources :motocategories
   resources :motomakes
   resources :powercategories
   resources :powermakes
   resources :autolistings
   resources :motolistings
   resources :marinelistings
   resources :powerlistings

end

app/models/autocategories.rb
class Autocategories < ActiveRecord::Base
  attr_accessible :category
	validates_presence_of :category
end

app/models/automailer.rb
class Automailer < ActionMailer::Base

default_url_options[:host] = "swapmywhip.com"  

  def welcome_email(user)
    subject    "Welcome to SwapMyWhip.com"
    recipients user.email
    from       "info@swapmywhip.com"
    sent_on    Time.now
    body 			 :user => user 
  end
  
  def new_message(message)
  	subject    "New Message at SwapMyWhip.com"
    recipients message.recipient.email
    from       "info@swapmywhip.com"
    sent_on    Time.now
    body 			 :message => message
  end
  
  def contact_us_message(message)
  	subject    "Message Sent Using 'Contact Us' Form: " + message.subject
    recipients ADMIN_EMAIL_ADDRESS
    from       message.email
    sent_on    Time.now
    body 			 :message => message
  end
  
  def password_reset_instructions(user)
  	subject			"Password Reset Instructions for your swapmywhip.com account"
  	recipients	user.email
  	from				"info@swapmywhip.com"
  	sent_on			Time.now
  	body				:edit_password_reset_url => edit_password_reset_url(user.perishable_token)
  end

end

app/models/automodels.rb
class Automodels < ActiveRecord::Base
  attr_accessible :make, :model
	validates_presence_of :make
	validates_presence_of :model
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :listing
end

app/models/listing.rb
class Listing < ActiveRecord::Base
	validates_presence_of :listingtype
	validates_numericality_of :price, :mileage, :allow_nil => true, :message => "is not a number or contains extra characters.  Please use only numbers."
	belongs_to :users
	belongs_to :owner, :class_name => "User", :foreign_key => "user_id"
	has_many :messages
	has_many :photos, :dependent => :destroy
	has_many :wishlists, :foreign_key => "user_id", :primary_key => "user_id"
#will_paginate stuff
	cattr_reader :per_page
  @@per_page = 50

	#default_scope :conditions => ["expired_at >= ?", Date.today]
end

app/models/marinemakes.rb
class Marinemakes < ActiveRecord::Base
  attr_accessible :make
	validates_presence_of :make
end

app/models/message.rb
class Message < ActiveRecord::Base
	validates_presence_of :recipient_id, :subject, :body
	belongs_to :sender, :class_name => "User", :foreign_key => "sender_id"
	belongs_to :recipient, :class_name => "User", :foreign_key => "recipient_id"
	belongs_to :listing
end

app/models/motocategories.rb
class Motocategories < ActiveRecord::Base
  attr_accessible :category
	validates_presence_of :category
end

app/models/motomakes.rb
class Motomakes < ActiveRecord::Base
  attr_accessible :make, :sort_order
	validates_presence_of :sort_order
	validates_presence_of :make
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	acts_as_fleximage do
		image_directory 'public/images/uploaded'
		image_storage_format :jpg
		use_creation_date_based_directories true
		
		preprocess_image do |image|
			image.resize '800x600'
		end
	end
	belongs_to :listing
end

app/models/powercategories.rb
class Powercategories < ActiveRecord::Base
  attr_accessible :category, :subcategory
	validates_presence_of :category
	validates_presence_of :subcategory
end

app/models/powermakes.rb
class Powermakes < ActiveRecord::Base
  attr_accessible :make, :sort_order
	validates_presence_of :sort_order
	validates_presence_of :make
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :email, :firstname, :lastname, :phone, :address, :address2, :city, :state, :zip, :username, :password,
                  :password_confirmation, :referred_by

	validates :firstname, :lastname, :phone, :address, :city, :state, :zip, :referred_by, :presence => true
	validates :zip, :length => { :in => 5..6 }

#can't make zip all numeric any more since Canadian Postal Codes are alphanumeric
	#validates_numericality_of :zip, :only_integer => true
	
	has_many :listings, :dependent => :destroy
	has_many :messages
	has_many :sent_messages, :class_name => "Message", :foreign_key => "sender_id", :conditions => ['sender_deleted_at IS NULL'], :order => "created_at DESC"
	has_many :received_messages, :class_name => "Message", :foreign_key => "recipient_id", :conditions => ['recipient_deleted_at IS NULL'], :order => "created_at DESC"
	has_many :unread_messages, :class_name => "Message", :foreign_key => "recipient_id", :conditions => ['read_at IS NULL AND recipient_deleted_at IS NULL'], :order => "created_at DESC"
	has_many :wishlists
	has_many :favorites
	#has_many :favorite_listings, :through => :favorites, :source => :listing
	acts_as_authentic
	
def deliver_password_reset_instructions!
	reset_perishable_token!
	Automailer.deliver_password_reset_instructions(self)
end

end

app/models/user_observer.rb
class UserObserver < ActiveRecord::Observer
	def after_create(user)
		Automailer.deliver_welcome_email(user)
	end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
	belongs_to :users
	validates_presence_of :listingtype
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "application", :except => :index
  def index
  	@featuredauto = Listing.first(:conditions => {:featured => true, :listingtype => 'auto'})
  	@featuredmoto = Listing.first(:conditions => {:featured => true, :listingtype => 'moto'})
  	@featuredmarine = Listing.first(:conditions => {:featured => true, :listingtype => 'marine'})
  	@featuredpower = Listing.first(:conditions => {:featured => true, :listingtype => 'power'})
  	
  	#@automakes = Automodels.find(:all, :order => 'make ASC', :select => 'distinct make')
  	#@automodels = ""
  	#@autocategories = Autocategories.all
  	#@search = Listing.new_search(params[:search]) TODO
    @search = Listing.all
    unless @search.blank?
      @listings = @search.all
      @listings_count = @search.count
    end

  	
  	render :action => "index", :layout => "home"
  end

  def faq
  end

  def about
  end

  def contact
  	@message = Message.new
  end
  
  def admin
  	@user = current_user
  	if @user
  		if @user.admin
  			render
  		else
  			flash[:notice] = 'Restricted Page'
  			redirect_to(root_url)
  		end
  	else
  		flash[:notice] = 'Restricted Page'
 			redirect_to(root_url)
 		end
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<table width="883" border="0" cellpadding="20" cellspacing="0">
	<tr>
		<td width="50%" align="left" valign="top">
      <p>The idea for <span class="smwText">SwapMyWhip.com</span> came to me out of pure frustration. I was in search of an alternative to the traditional methods of selling and buying vehicles. Buying a new car was always fun and exciting, but selling a car - ugh....I always dreaded that part of the process.
      </p>
      <p>I'd noticed ads on occasion for vehicle owners wishing to trade, but never found a site that was well organized and devoted to trading. And, working with dealerships and dealer websites - well, I never felt that I was getting good value for my trade in.
			</p>
			<p>So, the concept was born......
			</p>
			<p>I set out to put together a team of professionals - from programmers to graphic artists, and we collaborated on the project for the better part of a year, to ensure that every detail was perfect.
			</p>
		</td>
		<td width="50%" align="left" valign="top">
			<p>An enormous amount of time, energy and thoughtful design went into making <span class="smwText">Swap My Whip</span> a reality. We believe we've created the greatest system ever, to help you find a new ride,  and create a new home for your old one. At <span class="smwText">Swap My Whip</span>, we are obsessed with ensuring that every customer finds his or her right swap. From day one, our focus has been to offer our customers the opportunity to realize high value for their vehicle, in an environment that has never before offered it.
			</p>
			<p>This site has been designed to promote a sense of community to its users, with the hope that honesty and fairness will play a key role in all the transactions that transpire here. Please check us out - we think you'll love <span class="smwText">Swap My Whip</span> so much that you'll want to spread the word.
			</p>
			<p>
				<span class="greenText">Welcome! Now, go &quot;Get your Swap On!&quot; </span>
				<br />
			</p>
			<p>Daniel Krause</p>
		</td>
	</tr>
</table>

<div align="center">
	<a href="javascript:gotoshow()">
		<img src="../images/banners/MoparNation.jpg" name="slide" border=0 style="filter:blendTrans(duration=3)" width=382 height=60>
	</a>
	<a href="http://www.tkqlhce.com/click-3732474-10470862" target="_blank">
		<img src="http://www.ftjcfx.com/image-3732474-10470862" width="468" height="60" alt="Goodyear Mail-In Rebate" border="0"/>
	</a>
</div>

app/views/home/admin.html.erb
<table width="883" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td align="left" valign="top">
			<h2>Please select the object you wish to view/edit</h2>
			<p><%= link_to "Auto Categories", autocategories_path %></p>
			<p><%= link_to "Auto Makes/Models", automodels_path %></p>
			<p><%= link_to "Marine Categories", marinecategories_path %></p>
			<p><%= link_to "Marine Makes", marinemakes_path %></p>
			<p><%= link_to "Moto Categories", motocategories_path %></p>
			<p><%= link_to "Moto Makes", motomakes_path %></p>
			<p><%= link_to "Power Categories", powercategories_path %></p>
			<p><%= link_to "Power Makes", powermakes_path %></p>
			<p><%= link_to "Listings", listings_admin_url %></p>
		</td>
	</tr>
</table>

app/views/home/contact.html.erb
<table width="883" border="0" cellpadding="20" cellspacing="0">
	<% if flash[:notice] %>
		<div class="notice"><%= flash[:notice] %></div>
	<% end %>
	<tr>
		<td align="left" valign="top">
			<table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td width="60%" class="greenText">
						<p class="greenText">Like what you see? Have a question or comment? Like to advertise? Shoot us a quick message.<br />
							<br />
						</p>
						<p class="greenText">&nbsp;</p>
						<p class="greenText">&nbsp;</p>
						<% form_for @message, :url => {:controller => "messages", :action => "create"} do |f| %>
							<%= f.error_messages %>
							
							<%= f.hidden_field :recipient_id, :value => 1 %>
							<table width="100%" border="0" cellspacing="0" cellpadding="0">
								<tr>
									<td width="15%" class="formText">*Name:</td>
									<td width="85%" align="left" valign="top">
										<%= f.text_field :name, :size => 35, :tabindex => 1 %>
									</td>
								</tr>
								<tr>
									<td class="formText">*Email:</td>
									<td align="left" valign="top">
										<%= f.text_field :email, :size => 35, :tabindex => 2 %>
									</td>
								</tr>
								<tr>
									<td class="formText">Phone:</td>
									<td align="left" valign="top">
										<%= f.text_field :phone, :size => 35, :tabindex => 3 %>
									</td>
								</tr>
								<tr>
									<td class="formText">*Subject:</td>
									<td align="left" valign="top">
										<%= f.text_field :subject, :size => 35, :tabindex => 3 %>
									</td>
								</tr>
								<tr>
									<td class="formText">*Message:</td>
									<td align="left" valign="top">
										<%= f.text_area :body, :cols => 32, :rows => 10, :tabindex => 4 %>
									</td>
								</tr>
								<tr>
									<td>&nbsp;</td>
									<td align="left" valign="top" class="formText">*required</td>
								</tr>
								<tr>
									<td>&nbsp;</td>
									<td align="left" valign="top">
										<%= image_submit_tag "sendbutton.jpg", :alt => "submit", :size => "54x25", :border => 0 %>
									</td>
								</tr>
							</table>
							
						<% end %>
						
					</td>
					<td width="40%" align="right" valign="top">
						<p>Email:</p>
						<p><span class="smwText">info@swapmywhip.com</span></p>
						<p><span class="smwText">socialmedia@swapmywhip.com</span></p>
						<p>Atlanta, GA USA</p>
						<p>
							<img src="images/mot1.jpg" width="158" height="214" hspace="2" vspace="2" />
							<img src="images/jetski.jpg" width="165" height="214" hspace="2" vspace="2" />
						</p>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td align="center">
			<%= link_to image_tag("468x60_imgad.jpg", :alt => "AIM Mobile Inspections", :border => 0), "http://www.aimmobileinspections.com/SwapMyWhip-car-inspections.php", :popup => true %>
		</td>
	</tr>
</table>

app/views/home/forums.html.erb
<table width="883" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td align="center" valign="top">
			<p>Forums coming soon!</p>
			<p>
				Anyone wishing to moderate a forum for the following vehicles, please drop us an email @ <a href="mailto:info@swapmywhip.com">info@swapmywhip.com</a>:
				<br />
				Mustangs, Corvettes, Mopar, Camaros, Harley Davidson, Moto Guzzi, Porsche, Audi, VW, BMW Cars, BMW Motorcycles, Triumph Motorcycles, Victory Motorcycles
			</p>
		</td>
	</tr>
</table>

app/views/home/index.html.erb
<table width="883" border="0" cellpadding="0" cellspacing="0">
	<% if flash[:notice] %>
		<div class="notice"><%= flash[:notice] %></div>
	<% end %>
	<tr><br />
		<td align="center" valign="top">

			<div class="leftColumn">
				<p>
					<span style="font-weight: bold;">
						<strong>Ready to list your vehicle,<br />
										or contact an owner about<br />
										purchasing outright?
						</strong>
					</span>
					<br />
					<%= link_to "Register now", new_user_path, :style => "color:  #394a59;" %> and get started.
				</p>
				<p>
					<span>
						<strong>Just want to check us out?</strong>
					</span>
					<br />
					Click below under &quot;Quick Search.&quot;
				</p>
				<p>
					<%= link_to "How Our Site Works", faq_url, :style => "color:  #394a59; font-size: 12px; font-weight: bold;" %>
				</p>
				<p>
					<br />
					<span style="font-size: 17px; font-weight: bold;">Quick Search<br />for Whips</span>
					<br />
					See what was listed today.
				</p>
				<p>
                  <%unless @search.blank?%>
					<%= form_for @search, :url => {:controller => :autolistings, :action => "searchautos"} do |f| %>
						<%= f.hidden_field :order_by, :value => "created_at" %>
						<%= f.hidden_field :order_as, :value => "DESC" %>
						<% f.fields_for @search.conditions do |listings| %>
							<%= listings.hidden_field :listingtype_is, :value => "auto" %>
							<%= f.submit "Automobiles", :class => "browseLinkFormSubmit" %>
						<% end %>

					<% end %>

					<!--<%= link_to "Automobiles", searchautos_url, :style => "font-weight: bold; color: #823416;" %>-->
				</p>
				<p>
					<% form_for @search, :url => {:controller => :motolistings, :action => "searchmotos"} do |f| %>
						<%= f.hidden_field :order_by, :value => "created_at" %>
						<%= f.hidden_field :order_as, :value => "DESC" %>
						<% f.fields_for @search.conditions do |listings| %>
							<%= listings.hidden_field :listingtype_is, :value => "moto" %>
							<%= f.submit "Motorcycles", :class => "browseLinkFormSubmit" %>
						<% end %>
					<% end %>
					<!--<%= link_to "Motorcycles", searchmotos_url, :style => "font-weight: bold; color: #823416;" %>-->
				</p>
				<p>
					<% form_for @search, :url => {:controller => :marinelistings, :action => "marinelistingsresults"} do |f| %>
						<%= f.hidden_field :order_by, :value => "created_at" %>
						<%= f.hidden_field :order_as, :value => "DESC" %>
						<% f.fields_for @search.conditions do |listings| %>
							<%= listings.hidden_field :listingtype_is, :value => "marine" %>
							<%= f.submit "Marine", :class => "browseLinkFormSubmit" %>
						<% end %>
					<% end %>
					<!--<%= link_to "Marine", searchmarine_url, :style => "font-weight: bold; color: #823416;" %>-->
				</p>
				<p>
					<% form_for @search, :url => {:controller => :powerlistings, :action => "powerlistingsresults"} do |f| %>
						<%= f.hidden_field :order_by, :value => "created_at" %>
						<%= f.hidden_field :order_as, :value => "DESC" %>
						<% f.fields_for @search.conditions do |listings| %>
							<%= listings.hidden_field :listingtype_is, :value => "power" %>
							<%= f.submit "Powersports", :class => "browseLinkFormSubmit" %>
						<% end %>
					<% end %>
                  <%end%>
					<!--<%= link_to "Powersports", searchpower_url, :style => "font-weight: bold; color: #823416;" %>-->
				</p>
			</div>

			<div class="centerColumn">
				<center>
					<h2>
						<strong style="font-size: 1.4em;">The Vehicle Trading Marketplace</strong>
					</h2>
				</center>
				<span style="font-size: 1.2em; text-align: left; color: #000;">
					<p>
						Tired of the old way of finding a new ride?  Without cash, you have to sell your current ride first, or take a hit in the wallet when you trade it in. There's a better way...
					</p>
					<p>
						We created a website where YOU can get a better deal. <span class="smwText">SwapMyWhip.com</span> lets you swap your vehicle with other private owners (or just purchase outright). Whether you're upsizing, downsizing, found a new hobby, or just enjoy something new every year, this site has something for you.
					</p>
					<p>
						Swap as often as you'd like, because you'll get value when you swap!
Whatever your situation, you'll find that swapping for your next vehicle is the way to go!
					</p>
					<p>
						SwapMyWhip.com is free to use, so register today!
					</p>
				</span>
<!--				<p align="center">
					<a href="http://www.youtube.com/watch?v=xBq9FA_Z5Zg" target="_blank" style="font-size:16px; font-weight:bold; color:#823416;">
						Check out our YouTube video!
					</a>
				</p>
-->
				<p style="text-align: center">
					<span class="greenText">Ready, Set, Swap! Click a category below.</span>
				</p>
				<div id="socialNav">
          <a href="https://www.facebook.com/pages/Swap-My-Whip/117420464960200?ref=ts" title="Swap My Whip Facebook Page" class="facebook"></a>
          <a href="https://twitter.com/#!/SwapMyWhip" title="Follow us on Twitter" class="twitter"></a>
        </div>
			</div>
			
			<div class="rightColumn">
				<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="250" height="120" id="FlashID" title="free listing ad">
					<param name="movie" value="../flash/free_listing.swf" />
					<param name="quality" value="high" />
					<param name="wmode" value="opaque" />
					<param name="swfversion" value="6.0.65.0" />
				<!-- This param tag prompts users with Flash Player 6.0 r65 and higher to download the latest version of Flash Player. Delete it if you don’t want users to see the prompt. -->
					<param name="expressinstall" value="../Scripts/expressInstall.swf" />
				<!-- Next object tag is for non-IE browsers. So hide it from IE using IECC. -->
				<!--[if !IE]>-->
					<object type="application/x-shockwave-flash" data="../flash/free_listing.swf" width="250" height="120">
					<!--<![endif]-->
						<param name="quality" value="high" />
						<param name="wmode" value="opaque" />
						<param name="swfversion" value="6.0.65.0" />
						<param name="expressinstall" value="../Scripts/expressInstall.swf" />
					<!-- The browser displays the following alternative content for users with Flash Player 6.0 and older. -->
						<div>
							<h4>Content on this page requires a newer version of Adobe Flash Player.</h4>
								<p>
									<a href="http://www.adobe.com/go/getflashplayer">
										<img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" width="112" height="33" />
									</a>
								</p>
						</div>
					<!--[if !IE]>-->
					</object>
				<!--<![endif]-->
				</object>

				<table cellspacing="0">
					<tr>
						<td>
							<a href="http://www.hubcapandwheelworld.com" target="_blank">
								<img src="../images/banners/HubCap_Annie_Banner_250.jpg" border=0 width=250 height=52 alt="HubCap Annie">
							</a>
							<%= link_to image_tag("Abundant-Grounds.png", :border => 0), "http://www.facebook.com/pages/Swap-My-Whip/117420464960200", :popup => true, :alt => "Cars and Coffee" %>
<!--							<%= link_to image_tag("LostMtn-Cruise-in-banner.jpg", :border => 0), "http://www.facebook.com/pages/Swap-My-Whip/117420464960200", :popup => true, :alt => "Lostmtn cruise-in banner" %>
-->
						</td>
					</tr>
				</table>
			</div>
		</td>
	</tr>
</table>

app/views/home/whatitsworth.html.erb
<table width="883" border="0" cellpadding="20" cellspacing="0">
	<tr>
		<td align="left" valign="top">
			<p><strong><span class="smwText">Swap My Whip</span></strong> was founded on the principle of offering it's customers a value oriented method of vehicle exchange. The following websites have proven to be excellent sources for pricing and product reviews. If you find another site that you believe to be a great resource for vehicle values and reviews, please email us, and we'll list it here for everyone's benefit. Please use common sense, and do your due diligence - check prices on similar vehicles for sale using other sources, to determine "What it's worth".
			</p>
			<p>&nbsp;</p>
      <p>&nbsp;</p>
     	<table border="0" cellpadding="10" cellspacing="0">
     		<tr>
     			<td align="center">
			      <%= link_to image_tag("nadaguideslink.jpg", :alt => "new & used car prices, values, ratings & buying guides", :size => "175x107", :border => 0), "http://www.nadaguides.com/home.aspx?l=1&w=28&p=0&f=5000&custID=11161", :popup => true %>
	      		<br/>
			  	  <font face="Arial" size="2">
			  	  	<strong>New & Used Car Prices
					  	  <br />
					  	  at NADAguides.com
					  	</strong>
					  </font>
			    </td>
			    <td align="center">
     	      <%= link_to image_tag("kelleybluebooklink.gif", :alt => "Kelley Blue Book", :size => "207x65", :border => 0), "http://kbb.com", :popup => true %>
			    </td>
			  </tr>
			</table>
		</td>
    <td width="40%" align="right" valign="top">
    	<%= image_tag "atv_boat.png", :size => "253x330", :alt => "atv and boat", :border => 0 %>
    </td>
	</tr>
</table>